In [33]:
import cv2
import numpy as np

In [34]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'

In [35]:
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [36]:
center = (780, 250)
radius = 150 
color = (23,220, 75)
thickness = 3
lineType = cv2.LINE_8
shift = 0

img_circle=cv2.circle(img_resize, center, radius, color, thickness, lineType, shift)

In [37]:
cv2.imshow("Model Image", img_circle)
cv2.waitKey(0)
cv2.destroyAllWindows()

 the shift tells the computer how many decimal places you're using. For example, if you're using one decimal place (like 1.5), the shift would be 1 because you're dealing with one digit after the decimal point.

So, the shift helps the computer understand how detailed or precise your circle's position is by letting it know about the parts of numbers you're using, like fractions or decimals.

Fill Circle on Image

In [38]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
 
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [39]:
center = (780, 250)
radius = 150 
color = (23,220, 75)
thickness = -1
lineType = cv2.LINE_8
shift = 0

img_circle=cv2.circle(img_resize, center, radius, color, thickness, lineType, shift)

In [40]:
cv2.imshow("Model Image", img_circle)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

Draw 2 Circles

In [41]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [42]:
center = (780, 250)
radius = 130 
color = (23,220, 75)
thickness = 5
lineType = cv2.LINE_8
shift = 0

cv2.circle(img_resize, center, radius, color, thickness, lineType, shift)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [43]:
center2 = (640, 450)
radius2 = 80
color2 = (36,90,10)
 
cv2.circle(img_resize, center2, radius2, color2, thickness, lineType, shift)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [44]:
cv2.imshow("Model Image", img_resize)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

Draw Multiple Circles & Text

In [45]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [46]:
center = (780, 250)
radius = 130
color = (28,68,235)
thickness = 6
linetype = cv2.LINE_4
shift = 0
 
color2 = (2555,0,0)
radius2 = 120
 
color3 = (0,255,0)
radius3 = 110
 
color4 = (0,0,255)
radius4 = 100
 
color5 = (85,87,93)
radius5 = 90
 
color6 = (65,207,203)
radius6 = 80
 
color7 = (65,207,203)
radius7 = 80

In [47]:
cv2.circle(img_resize, center, radius, color, thickness, linetype, shift)
cv2.circle(img_resize, center, radius2, color2, thickness, linetype, shift)
cv2.circle(img_resize, center, radius3, color3, thickness, linetype, shift)
cv2.circle(img_resize, center, radius4, color4, thickness, linetype, shift)
cv2.circle(img_resize, center, radius5, color5, thickness, linetype, shift)
cv2.circle(img_resize, center, radius6, color6, thickness, linetype, shift)
cv2.circle(img_resize, center, radius7, color7, thickness, linetype, shift)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [48]:
cv2.putText(img_resize, "Model Face", (410, 110), cv2.FONT_HERSHEY_COMPLEX_SMALL, 3, (0,255,0), 3)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [49]:
cv2.imshow("Model Image", img_resize)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
cv2.imwrite('multiple_circle_pic.jpg',img_resize)

True