In [2]:
import cv2
import numpy as np

Draw Ellipse on Image

In [3]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [6]:
center = (800, 230)
axes = (100, 200)
angle = 30
startAngle = 0
endAngle = 360
color = (12,200,43)
thickness = 4

cv2.ellipse(img_resize, center, axes, angle, startAngle, endAngle, color, thickness)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [7]:
cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

Fill Ellipse

In [8]:
center = (800, 230)
axes = (100, 200)
angle = 30
startAngle = 0
endAngle = 360
color = (12,200,43)
thickness = -1

cv2.ellipse(img_resize, center, axes, angle, startAngle, endAngle, color, thickness)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [9]:
cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

Incomplete Ellipse Arc

In [10]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [11]:
center = (500, 230)
axes = (100, 200)
angle = 30
startAngle = 100
endAngle = 360
color = (12,200,43)
thickness = -1
 
cv2.ellipse(img_resize, center, axes, angle, startAngle, endAngle, color, thickness)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [12]:

cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

Incomplete Empty Ellipse Arc

In [13]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [14]:
center = (500, 230)
axes = (100, 200)
angle = 30
startAngle = 100
endAngle = 360
color = (12,200,43)
thickness = 33
cv2.ellipse(img_resize, center, axes, angle, startAngle, endAngle, color, thickness)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [15]:
 
cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

Ellipse And Text

In [16]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [17]:
center = (500, 230)
axes = (100,200)
angle = 30
startAngle = 0
endAngle = 340
color = (56,208,23)
thickness = 5

cv2.ellipse(img_resize, center, axes, angle, startAngle, endAngle, color, thickness)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [18]:
cv2.putText(img_resize, "Model Smile", (600, 280), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, 2, (34,200,200), 3)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [19]:
cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()