In [1]:
import cv2
import numpy as np

Line On Image

In [2]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [3]:
pt1 = (500, 140)
pt2 = (1050, 140)
color = (23,200,54)
thickness = 50

cv2.line(img_resize, pt1, pt2, color, thickness)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [4]:
cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

Draw 2 lines on Image

In [5]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [6]:
pt1 = (500, 140)
pt2 = (1050, 140)
color = (23,200,54)
thickness = 50

thickness2 = 5
color2 = (12,43,200)

In [7]:
cv2.line(img_resize, pt1, pt2, color, thickness)
cv2.line(img_resize, pt1, pt2, color2, thickness2)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [8]:
cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

Draw multiple lines on Image

In [9]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [12]:
pt1 = (500, 140)
pt2 = (1050, 140)
color = (23,200,54)
thickness = 50

thickness2 = 20
color2 = (12,43,200)

thickness3 =10
color3=(200,20,20)

thickness4=5
color4=(100,100,100)

In [13]:
cv2.line(img_resize, pt1, pt2, color, thickness)
cv2.line(img_resize, pt1, pt2, color2, thickness2)
cv2.line(img_resize, pt1, pt2, color3, thickness3)
cv2.line(img_resize, pt1, pt2, color4, thickness4)
 

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [14]:
cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
cv2.imwrite('multiple_lines.png',img_resize)

True

Line and Text on Image

In [16]:
img_path=r'C:\Users\Pramod Rai\Desktop\opencv_ai_production\opencv_ai_production\images\pexels-bess-hamiti-35537.jpg'
image = cv2.imread(img_path)
img_resize = cv2.resize(image, (1280,720))

In [17]:
pt1 = (500, 140)
pt2 = (1050, 140)
color = (34,200,93)
thickness = 8

cv2.line(img_resize, pt1, pt2, color, thickness)

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [18]:
cv2.putText(img_resize, "Model Smile", (600, 120), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, 2, (34,200,200), 3)
 

array([[[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[19,  7,  7],
        [19,  7,  7],
        [18,  6,  6],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       [[18,  6,  6],
        [18,  6,  6],
        [19,  7,  7],
        ...,
        [23, 17, 14],
        [24, 17, 14],
        [24, 17, 14]],

       ...,

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]],

       [[27, 18,  8],
        [27, 18,  8],
        [27, 18,  8],
        ...,
        [33, 27, 22],
        [33, 27, 22],
        [33, 27, 22]]], dtype=uint8)

In [19]:
cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
cv2.imwrite("text_on_line.png",img_resize)

True